-- V20260406_01__appointment_module_schema.sql
-- Scope: appointments, appointment_slots, doctor_schedule_templates, doctor_availability(id only)

BEGIN;

-- 1) doctor_availability: add surrogate id needed by private appointment module
ALTER TABLE doctor_availability
    ADD COLUMN IF NOT EXISTS id BIGINT;

CREATE SEQUENCE IF NOT EXISTS doctor_availability_id_seq;

ALTER TABLE doctor_availability
    ALTER COLUMN id SET DEFAULT nextval('doctor_availability_id_seq');

UPDATE doctor_availability
   SET id = nextval('doctor_availability_id_seq')
 WHERE id IS NULL;

ALTER TABLE doctor_availability
    ALTER COLUMN id SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        WHERE c.conname = 'uk_doctor_availability_id'
          AND t.relname = 'doctor_availability'
    ) THEN
        ALTER TABLE doctor_availability
            ADD CONSTRAINT uk_doctor_availability_id UNIQUE (id);
    END IF;
END $$;

-- Keep/ensure logical uniqueness per doctor/date used by upsert logic
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        WHERE c.conname = 'uk_doctor_availability_doctor_date'
          AND t.relname = 'doctor_availability'
    ) THEN
        ALTER TABLE doctor_availability
            ADD CONSTRAINT uk_doctor_availability_doctor_date UNIQUE (doctor_id, available_date);
    END IF;
END $$;

-- 2) doctor_schedule_templates: recurring weekly schedule templates
CREATE TABLE IF NOT EXISTS doctor_schedule_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id BIGINT NOT NULL,
    day_of_week INTEGER NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        WHERE c.conname = 'uk_doctor_schedule_templates_doctor_day'
          AND t.relname = 'doctor_schedule_templates'
    ) THEN
        ALTER TABLE doctor_schedule_templates
            ADD CONSTRAINT uk_doctor_schedule_templates_doctor_day
            UNIQUE (doctor_id, day_of_week);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        WHERE c.conname = 'fk_doctor_schedule_templates_doctor'
          AND t.relname = 'doctor_schedule_templates'
    ) THEN
        ALTER TABLE doctor_schedule_templates
            ADD CONSTRAINT fk_doctor_schedule_templates_doctor
            FOREIGN KEY (doctor_id) REFERENCES doctors(id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_doctor_schedule_templates_doctor_id
    ON doctor_schedule_templates(doctor_id);

-- 3) appointment_slots: generated/bookable time slots
CREATE TABLE IF NOT EXISTS appointment_slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_availability_id BIGINT NULL,
    doctor_id BIGINT NOT NULL,
    slot_date DATE NOT NULL,
    slot_start_time TIME NOT NULL,
    slot_end_time TIME NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE'
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        WHERE c.conname = 'uk_appointment_slots_doctor_date_start'
          AND t.relname = 'appointment_slots'
    ) THEN
        ALTER TABLE appointment_slots
            ADD CONSTRAINT uk_appointment_slots_doctor_date_start
            UNIQUE (doctor_id, slot_date, slot_start_time);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        WHERE c.conname = 'fk_appointment_slots_doctor'
          AND t.relname = 'appointment_slots'
    ) THEN
        ALTER TABLE appointment_slots
            ADD CONSTRAINT fk_appointment_slots_doctor
            FOREIGN KEY (doctor_id) REFERENCES doctors(id);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        WHERE c.conname = 'fk_appointment_slots_doctor_availability'
          AND t.relname = 'appointment_slots'
    ) THEN
        ALTER TABLE appointment_slots
            ADD CONSTRAINT fk_appointment_slots_doctor_availability
            FOREIGN KEY (doctor_availability_id) REFERENCES doctor_availability(id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_appointment_slots_doctor_date_status
    ON appointment_slots(doctor_id, slot_date, status);

CREATE INDEX IF NOT EXISTS idx_appointment_slots_doctor_availability_id
    ON appointment_slots(doctor_availability_id);

-- 4) appointments: link appointment to a generated slot
ALTER TABLE appointments
    ADD COLUMN IF NOT EXISTS slot_id BIGINT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        WHERE c.conname = 'fk_appointments_slot'
          AND t.relname = 'appointments'
    ) THEN
        ALTER TABLE appointments
            ADD CONSTRAINT fk_appointments_slot
            FOREIGN KEY (slot_id) REFERENCES appointment_slots(id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_appointments_slot_id
    ON appointments(slot_id);

COMMIT;